### ISSUE TITLE
In vrf2.5, I through Interactions.s.sol's `CreateSubscription: : CreateSubscription` returns and the actual different subId

### ISSUE THREAD

**Issue by segonse** [Cyfrin/foundry-smart-contract-lottery-cu#62]
### this is my code
![image](https://github.com/user-attachments/assets/d4585745-3708-4053-96aa-f246b254ff96)

### this is execute `make createSubscription ARGS="--network sepolia"` echo
![image](https://github.com/user-attachments/assets/f6116a37-5ead-4f26-9869-26cfb6b8d317)
![image](https://github.com/user-attachments/assets/9a17d6fe-8b6c-497a-bd1a-c02e29c53dcf)

### this is my chianlink create subscription, It is created by the command just executed, only the subid on chainlink can be properly funded
![image](https://github.com/user-attachments/assets/b7e64b5c-f5a8-41d1-a119-386a25727fd1)

**Comment by cromewar** [comment]
Hello @segonse, thanks for posting this. It seems that you are having a mismatch between the subscription ID you are generating and the one you have on Chainlink.

I would like to have more context here, are you using the same wallet address on both?
can you share the entire code and script you are using the execute this?

In my impression, there might be a mismatch in the execution of both steps, making the process use two different IDs, but I'm not sure, so I would like you to share your code first. 

cheers.

**Comment by segonse** [comment]
> Hello @segonse, thanks for posting this. It seems that you are having a mismatch between the subscription ID you are generating and the one you have on Chainlink.
> 
> I would like to have more context here, are you using the same wallet address on both? can you share the entire code and script you are using the execute this?
> 
> In my impression, there might be a mismatch in the execution of both steps, making the process use two different IDs, but I'm not sure, so I would like you to share your code first.
> 
> cheers.

ok，this is my test code:
https://github.com/segonse/smart-contract-lottery/tree/vrf-v2.5

executed command:
forge script script/Interactions.s.sol:CreateSubscription ARGS="--network sepolia"

**Comment by cromewar** [comment]
have you created the subscription ID with the same wallet that you are using for sending the transaction?

**Comment by segonse** [comment]
> have you created the subscription ID with the same wallet that you are using for sending the transaction?

yes. And my subscription in chainlink created after the script was executed, should not be different account.

**Comment by spencerj411** [comment]
@segonse Good catch! I discovered the same thing. From my understanding, this is because `forge` simulates the on-chain execution first (the first subscription ID). Then, it provides you another trace is from `forge` giving you a "prediction" of how the actual on-chain execution of the script will go (the second subscription ID); along with estimated gas costs.

The actual execution of the transactions from our script will not have a trace in the output. You would need to check the transaction hash on the blockchain explorer of the network you ran the script on to check events etc. Also, "console" is a foundry thing, therefore, you won't be able to get that as output either. You would have to check the `SubscriptionCreated` event on the explorer or the Chainlink UI to get the actual subscription ID. 

The following is a response I got from ChatGPT when I was trying to figure this out:

> Initial Traces (Simulation): The detailed traces you see during the execution of forge script are from Foundry's simulation environment.
> Simulated On-Chain Traces: These are a preview of what would happen on-chain, provided after the simulation but before actual on-chain execution.
> Actual On-Chain Logs: These are the real execution logs from the blockchain after the script is broadcasted and executed on the network. 

Let me know if this helps!

**Comment by segonse** [comment]
> @segonse Good catch! I discovered the same thing. From my understanding, this is because `forge` simulates the on-chain execution first (the first subscription ID). Then, it provides you another trace is from `forge` giving you a "prediction" of how the actual on-chain execution of the script will go (the second subscription ID); along with estimated gas costs.
> 
> The actual execution of the transactions from our script will not have a trace in the output. You would need to check the transaction hash on the blockchain explorer of the network you ran the script on to check events etc. Also, "console" is a foundry thing, therefore, you won't be able to get that as output either. You would have to check the `SubscriptionCreated` event on the explorer or the Chainlink UI to get the actual subscription ID.
> 
> The following is a response I got from ChatGPT when I was trying to figure this out:
> 
> > Initial Traces (Simulation): The detailed traces you see during the execution of forge script are from Foundry's simulation environment.
> > Simulated On-Chain Traces: These are a preview of what would happen on-chain, provided after the simulation but before actual on-chain execution.
> > Actual On-Chain Logs: These are the real execution logs from the blockchain after the script is broadcasted and executed on the network.
> 
> Let me know if this helps!

thank you！Fortunately, I went to the chainlink web page and looked at my subscription id

**Comment by natsu2912** [comment]
Hello,

I don't think the "wrong subscription ID" is returned in the "Simulation step", and the "correct subscription ID" is returned in the "Simulated On-Chain".

Why do I think that? Because after my program receive the subscription ID, it continue to use it to fund this subscription. I will not post the full code here because it is too long. However, below is the function "deployContract" which do these things
1. Create the subcription
2. Fund the subscription
3. Deploy the Raffle contract
4. Add the above Raffle contract to be the subscription's consumer

If you need to check my full code, please follow [this repo](https://github.com/natsu2912/natsu-foundry-smart-contract-lottery)

And 1 more thing: when running "forge test --fork-url" with the local Anvil chain, another error occurs. You can check my comment at this [issue](https://github.com/Cyfrin/foundry-smart-contract-lottery-cu/issues/74#issuecomment-2797253851) for . It is still open.

This is the function "deployContract" mentioned above
``` solidity
function deployContract() public returns (Raffle, HelperConfig) {
    // Get or create network configuration
    HelperConfig helperConfig = new HelperConfig();
    HelperConfig.NetworkConfig memory networkConfig = helperConfig
        .getActiveNetworkConfig();
    // Create subcription if we don't have one
    CreateSubscription subscriptionCreator;
    if (networkConfig.subscriptionId == 0) {
        subscriptionCreator = new CreateSubscription();
        (
            networkConfig.subscriptionId, // Set subscriptionId after creation
            networkConfig.vrfCoordinator // Set vrfCoordinator after creation
        ) = subscriptionCreator
            .createSubscriptionUsingVrfCoordinatorAddress(
                address(networkConfig.vrfCoordinator),
                networkConfig.deployerAccount
            );
    }
    // Set the new value to the state variables in the HelperConfig contract
    helperConfig.setSubIdForActiveNetworkConfig(
        networkConfig.subscriptionId
    );
    helperConfig.setVrfCoordinatorForActiveNetworkConfig(
        networkConfig.vrfCoordinator
    );
    // Fund subscription if LINK < 5 ether
    uint256 MINIMUM_LINK_AMOUNT = 300 ether; // 300 LINK
    uint256 LINK_AMOUNT_TO_FUND = 300 ether; // 300 LINK
    (uint256 current_subscription_balance, , , , ) = VRFCoordinatorV2_5Mock(
        networkConfig.vrfCoordinator
    ).getSubscription(networkConfig.subscriptionId);
    if (current_subscription_balance < MINIMUM_LINK_AMOUNT) {
        FundSubscription subscriptionFunder = new FundSubscription();
        subscriptionFunder.fundSubscription(
            networkConfig.vrfCoordinator,
            networkConfig.subscriptionId,
            LINK_AMOUNT_TO_FUND,
            networkConfig.linkTokenContract,
            networkConfig.deployerAccount
        );
    }
    // Deploy the Raffle contract
    vm.startBroadcast();
    Raffle raffle = new Raffle(
        networkConfig.entranceFee,
        networkConfig.interval,
        networkConfig.vrfCoordinator,
        networkConfig.gasLane,
        networkConfig.subscriptionId,
        networkConfig.callbackGasLimit
    );
    vm.stopBroadcast();
    // Add Raffle contract as consumer
    AddConsumer consumerAdder = new AddConsumer();
    // Don't need to broadcast here...
    consumerAdder.addConsumer(
        networkConfig.vrfCoordinator,
        networkConfig.subscriptionId,
        address(raffle),
        networkConfig.deployerAccount
    );
    // Return
    return (raffle, helperConfig);
}
```
